export default ({ color }) => ({
  dropdown: {
    backgroundColor: color.primary,
    color: color.text,
    position: 'relative',
    width: '140px',
    height: '40px',
    cursor: 'pointer',
    marginRight: '4px',
    marginLeft: '4px',
    outline: 'none',
    fontSize: '1em',
  },
  label: {
    width: '100%',
    height: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    textOverflow: 'hidden',
    userSelect: 'none',
    marginLeft: '7px',
    textTransform: 'capitalize',
    textAlign: 'center',
  },
  list: {
    listStyle: 'none',
    position: 'absolute',
    background: color.primary,
    left: 0,
    top: '40px',
    minHeight: '60px',
    margin: 0,
    padding: 0,
    width: '100%',
  },
  listItem: {
    padding: '10px 12px',
    color: color.text,
    textTransform: 'capitalize',
    ':hover': {
      background: color.highlight,
      color: color.primary,
    },
  },
  icon: {
    marginLeft: 'auto',
    marginRight: '15px',
    alignSelf: 'center',
    fontSize: '24px',
  },
  selectedText: {
    width: '100%',
  },
});
