export default ({ color }) => ({
  search: {
    marginLeft: 'auto',
    marginRight: 'auto',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    // marginTop: '15px',
  },
  input: {
    minWidth: '750px',
    maxWidth: '800px',
    height: '45px',
    // border: `2px solid ${color.primary}`,
    border: 'none',
    borderRadius: '2px',
    borderStyle: 'none',
    paddingLeft: '8px',
    fontSize: '1em',
    alignSelf: 'flex-start',
    background: 'rgba(255,255,255,0.9)',
    transition: 'all 0.25s',
    ':focus': {
      background: 'rgba(255,255,255,1)',
      boxShadow: '0px 0px 10px 1px #fff',
      outline: 'none',
    },
  },
  button: {
    border: 'none',
    borderRadius: '10%',
    background: 'none',
    display: 'flex',
    alignItems: 'center',
    cursor: 'pointer',
    position: 'absolute',
    right: 0,
    fontSize: '2em',
    outline: 'none',
  },
  icon: {
  },
  cog: {
    position: 'absolute',
    top: '50%',
    transform: 'translateY(-50%)',
  },
});
