export default ({ color }) => ({
  radioItem: {
    marginLeft: '5px',
    marginRight: '5px',
    width: '100%',
    // paddingLeft: '10px',
    position: 'relative',
    zIndex: 2,
    ':hover': {
      // background: color.secondary,
    },
    ':after': {
      // border: `1px solid ${color.primary}`,
      borderRadius: '30%',
      content: '""',
      display: 'inline-block',
      height: '25px',
      left: 0,
      position: 'absolute',
      top: '50%',
      transform: 'translateY(-50%)',
      width: '25px',
      zIndex: -1,
    },
    ':before': {
      background: '#fff',
      borderRadius: '50%',
      content: '""',
      display: 'inline-block',
      left: 4,
      position: 'absolute',
      top: '50%',
      transform: 'translateY(-50%)',
      transition: 'all 0.1s ease',
      height: '23px',
      width: '23px',
      zIndex: -1,
    },
  },
  radioOn: {
    ':before': {
      background: color.primary,
    },
  },
  radioNative: {
    visibility: 'hidden',
    display: 'none',
  },
  radioLabel: {
    cursor: 'pointer',
    width: '100%',
    display: 'block',
    textAlign: 'left',
    paddingLeft: '35px',
    userSelect: 'none',
  },
});
