export default ({ color }) => ({
  options: {
    color: '#fff',
    height: '280px',
    position: 'absolute',
    top: '55px',
    left: '-1px',
    width: '100%',
    fontSize: '14px',
    outline: 'none',
    background: 'none',
    ':focus': {
    },
  },
  optionsWrapper: {
    alignItems: 'center',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    height: '100%',
    borderRadius: '1px',
    width: '100%',
    background: '#0a2231',
  },
  header: {
    margin: 0,
    width: '100%',
    textAlign: 'left',
    marginBottom: '30px',
    height: '20%',
    lineHeight: '45px',
    background: 'linear-gradient(to right, #144463 0%, #0a2231 100%)',
  },
  h2: {
    margin: 0,
    paddingLeft: '8px',
    fontSize: '1.25em',
    fontWeight: 'normal',
  },
  table: {
    borderCollapse: 'collapse',
    tableLayout: 'fixed',
    width: '100%',
    height: '80%',
  },
  table2: {
    borderCollapse: 'collapse',
    tableLayout: 'fixed',
    width: '100%',
  },
  tbody: {
    width: '100%',
  },
  row: {
  },
  column: {
    height: '70px',
    textAlign: 'right',
  },
  open: {
    visibilty: 'visible',
    opacity: 1,
    zIndex: '100',
  },
  close: {
    visibilty: 'hidden',
    opacity: 0,
    zIndex: '-100',
  },
  btnClose: {
    position: 'absolute',
    border: 'none',
    background: 'none',
    color: 'rgba(255,255,255,0.7)',
    fontSize: '1.7em',
    right: '1px',
    top: '10px',
    cursor: 'pointer',
    ':hover': {
      color: 'rgba(255,255,255,1)',
    },
    outline: 'none',
  },
  screen: {
    position: 'fixed',
    zIndex: -1,
    left: 0,
    top: 0,
    background: 'rgba(0,0,0,0.80)',
    width: '100%',
    height: '100%',
  },
});
